[general]
import = [
  "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml",
]

[window]

dimensions = {columns = 160, lines = 50}
opacity = 0.9
padding = {x = 10, y = 10}
position = {x = 100, y = 10}

[font]

bold.family = "Fira Code"
bold_italic.family = "Fira Code"
italic.family = "Fira Code"
normal.family = "Fira Code"

size = 12.0

offset = {x = 0, y = 3}
