#!/bin/bash

# 現在のブランチが main かどうかをチェック
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "main" ]; then
  exit 0
fi

# git cleanup を実行
git cleanup

# package.json が存在するかチェック
if [ -f "package.json" ]; then
  if [ -f "pnpm-lock.yaml" ]; then
    echo "pnpm-lock.yaml found. Running pnpm install..."
    pnpm install
  else
    echo "package.json found. Running npm install..."
    npm install
  fi
fi
