" Make Vim more useful
set nocompatible

" Allow cursor keys in insert mode
set esckeys

" Allow backspace in insert mode
set backspace=indent,eol,start

" Encoding & Format
set fileencodings=utf-8,cp932,enc-jp,iso-2022-jp
set encoding=utf-8
set fileformats=unix,dos,mac
if exists('&ambiwidth')
    set ambiwidth=double
endif

" Don't add empty newlines at the end of files
set binary
set noeol

" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
  set undodir=~/.vim/undo
endif

" Enable line numbers
set number

" Enable syntax highlighting
syntax on
colorscheme Tomorrow-Night-Bright

" Make tabs as wide as two spaces
set tabstop=2

" Number of spaces for each step of autoindent
set shiftwidth=2

" Smart autoindenting
set smartindent

" a <Tab> in front of a line inserts blanks according to 'shiftwidth'.
set smarttab

" a <Tab> is changed to spaces
set expandtab

" Show "invisible" characters
set list
set listchars=tab:>.,precedes:<,extends:>

" Highlight searches
set hlsearch

" Ignore case of searches
set ignorecase

" Highlight dynamically as pattern is typed
set incsearch

" Always show a status line
set laststatus=2

" Customize the status line (Show character endoding and filemode)
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P

" Enable mouse in all modes
"set mouse=a

" Show the cursor position
set ruler

" Show the current mode
set showmode

" Show the filename in the window titlebar
" set title

" Show the (partial) command as it's begin typed
set showcmd

" Automatic commands
if has("autocmd")
  " Enable file type detection
  filetype on
  
  " Treat .json files as .js
  autocmd BufNewFile,BufRead *.json set filetype=json syntax=javascript
  
  " Treat .psgi files as perl
  autocmd BufNewFile,BufRead *.psgi set filetype=perl

  " Treat sass files
  autocmd BufNewFile,BufRead *.scss set filetype=scss

  " Restore a cursor position
  autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif
endif
