brew install coreutils
brew install colordiff
brew install ffmpeg
brew install jq
brew install openssl
brew install tree
brew install wget
brew install shellcheck
brew install shfmt
brew install go
brew install gh
brew install pnpm
