brew install --cask alfred
brew install --cask appcleaner
brew install --cask choosy
brew install --cask coteditor
brew install --cask dropbox
brew install --cask discord
brew install --cask figma
brew install --cask firefox
brew install --cask google-chrome
brew install --cask google-japanese-ime
brew install --cask grammarly
brew install --cask imageoptim
brew install --cask iterm2
brew install --cask kindle
brew install --cask miro
brew install --cask muzzle
brew install --cask notion
brew install --cask sidenotes
brew install --cask spotify
brew install --cask sync
brew install --cask tandem
brew install --cask visual-studio-code
brew install --cask zoomus
