brew install alfred
brew install appcleaner
brew install choosy
brew install coteditor
brew install dropbox
brew install discord
brew install figma
brew install firefox
brew install google-chrome
brew install google-japanese-ime
brew install imageoptim
brew install iterm2
brew install kindle
brew install notion
brew install sync
brew install visual-studio-code
brew install zoom
