brew cask install alfred
brew cask install appcleaner
brew cask install dropbox
brew cask install firefox
brew cask install homebrew/cask-versions/google-chrome-canary
brew cask install google-japanese-ime
brew cask install grammarly
brew cask install imageoptim
brew cask install iterm2
brew cask install itsycal
brew cask install licecap
brew cask install notion
brew cask install sketch
brew cask install simplecap
brew cask install spotify
brew cask install sync
brew cask install visual-studio-code
brew cask install zoomus
