brew tap homebrew/cask-fonts
brew install font-bitter
brew install font-fira-code
brew install font-fira-sans
brew install font-inconsolata
brew install font-lato
brew install font-libre-franklin
brew install font-montserrat
brew install font-noto-sans-cjk-jp
brew install font-oswald
brew install font-open-sans
brew install font-roboto
brew install font-roboto-condensed
brew install font-roboto-mono
brew install font-source-code-pro
