# Compile .zshrc automatically
# ----------------------------------------------------------------------

if [ ~/.zshrc -nt ~/.zshrc.zwc ]; then
  zcompile ~/.zshrc
fi

# Setup pure prompt
# ----------------------------------------------------------------------

autoload -U promptinit; promptinit
prompt pure

# Set path
# ----------------------------------------------------------------------

path=($HOME/bin(N-/) /usr/local/bin(N-/) /usr/local/opt/coreutils/libexec/gnubin(N-/) /usr/local/opt/openssl/bin(N-/) $path)

# Set alias
# ----------------------------------------------------------------------

alias ls="ls --color=auto -AF"
alias ll="ls -l"
alias tree='tree -F --dirsfirst -C'
alias diff="colordiff -s"

# Exports
# ----------------------------------------------------------------------

# Japanese and use UTF-8
export LANG="ja_JP.UTF-8"

# Use vim as the default editor
export EDITOR="vim"

# Unset default LS_COLORS
unset LS_COLORS

# History
# ----------------------------------------------------------------------

HISTFILE=${HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# Ignore some commands
HISTORY_IGNORE="(ls|ll|pwd|exit)"

# ヒストリに追加されるコマンド行が古いものと同じなら古いものを削除
setopt hist_ignore_all_dups

# スペースで始まるコマンド行はヒストリリストから削除
setopt hist_ignore_space

# ヒストリを呼び出してから実行する間に一旦編集可能
setopt hist_verify

# 余分な空白は詰めて記録
setopt hist_reduce_blanks

# 古いコマンドと同じものは無視
setopt hist_save_no_dups

# historyコマンドは履歴に登録しない
setopt hist_no_store

# 補完時にヒストリを自動的に展開
setopt hist_expand

# 履歴を追加
setopt append_history

# 複数シェル間で履歴を共有
setopt share_history

# 履歴をインクリメンタルに追加
setopt inc_append_history

# nvm
# ----------------------------------------------------------------------

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# ruby
# ----------------------------------------------------------------------

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)" # add --no-rehash flag to stop rehashing


# zsh-autosuggestions
# ----------------------------------------------------------------------

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh-autocompletions
# ----------------------------------------------------------------------

fpath=(/usr/local/share/zsh-completions $fpath)


# hub, git-completion, hub-completion
# ----------------------------------------------------------------------

eval "$(hub alias -s)"
fpath=(~/.zsh/completion $fpath)
autoload -U compinit && compinit

# case insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z} r:|[-_.]=**'

# Ubie Eng-Tools
# ----------------------------------------------------------------------
export PATH="$HOME/Projects/ubie-inc/eng-tools:$PATH"

# To profiling zsh
# ----------------------------------------------------------------------

#if type zprof > /dev/null 2>&1; then
#  zprof | less
#fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jimbo/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jimbo/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jimbo/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jimbo/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/sbin:$PATH"
