#!/usr/bin/env bash

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Share bash history across terminals (thanks @iandeth)
#function share_history {
#    history -a
#    history -c
#    history -r
#}
#PROMPT_COMMAND='share_history'
#shopt -u histappend
