#!/usr/bin/env bash

# USER
export USER="jmblog"

# Japanese and use UTF-8
export LANG="ja_JP.UTF-8"

# Use vim as the default editor
export EDITOR="vim"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoreboth:erasedups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:ll:ll *;cd:cd -:pwd:exit:date:* --help:history"

# Unset default LS_COLORS
unset LS_COLORS

# Change the directories to install apps with Homebrew Cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"
