#!/usr/bin/env bash
DOTFILES_DIRECTORY="${HOME}/.dotfiles"
source ${DOTFILES_DIRECTORY}/lib/utils

dirs_to_prepend=(
  "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
)

if is_osx; then
  dirs_to_prepend=("${dirs_to_prepend[@]}" "$(brew --prefix coreutils)/libexec/gnubin") # Add brew-installed GNU core utilities bin
fi

dirs_to_append=(
  "/usr/bin"
  "$HOME/bin"
  "$HOME/.dotfiles/bin"
  "$HOME/.nodebrew/current/bin" # Add nodebrew bin
  "$HOME/.rbenv/bin" # Add rbenv bin
)

for i in ${!dirs_to_prepend[*]}
do
  if [ -d ${dirs_to_prepend[$i]} ]; then
    PATH="${dirs_to_prepend[$i]}:$PATH"
  fi
done

for i in ${!dirs_to_append[*]}
do
  if [ -d ${dirs_to_append[$i]} ]; then
    PATH="$PATH:${dirs_to_append[$i]}"
  fi
done

unset dirs_to_prepend dirs_to_append

export PATH
