#!/usr/bin/env bash

files=(
  $HOME/.dotfiles/lib/utils         # Utils
  $HOME/.dotfiles/bash/bash_options # Options
  $HOME/.dotfiles/bash/bash_exports # Exports
  $HOME/.dotfiles/bash/bash_aliases # Aliases
  $HOME/.dotfiles/bash/functions/*  # Functions
  $HOME/.dotfiles/bash/bash_prompt  # Custom bash prompt
  $HOME/.bash_profile.local         # Local and private settings not under version control (e.g. git credentials)
  $HOME/.dotfiles/bash/bash_paths   # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for i in ${!files[*]}
do
  if [[ -r ${files[$i]} ]]; then
    source ${files[$i]}
  fi
done

unset files

# Init rbenv
if type_exists rbenvs; then
  eval "$(rbenv init -)"
fi

# Bash completion (Latest bash-completion needs bash 4.1+, but osx still uses bash 3.x. Bash 4 will be installed via Homebrew.)
if [[ ! "$BASH_VERSION" =~ ^4 ]]; then
  echo -e "\x1B[31mYou use bash 3.x. If you want to use Bash completion, update to 4.1+.\x1B[39m"
else
  if [ -f $HOME/.dotfiles/bash/bash-completion/bash_completion ]; then
    . $HOME/.dotfiles/bash/bash-completion/bash_completion
  fi
fi

# Git completion
if  [ -f $HOME/.dotfiles/git/git-completion.bash ]; then
  source $HOME/.dotfiles/git/git-completion.bash
fi

