#!/usr/bin/env bash

alias ls="ls --color=auto -AF"
alias ll="ls -l"
alias tree='tree -F --dirsfirst -C'
alias diff="colordiff -s"

if type_exists gtime; then
  alias time="gtime -f '%U user | %S system | %E elapsed | %P CPU'"
fi

if type_exists htop; then
  alias top="htop"
fi

alias git=hub

alias hlj="pbpaste | pygmentize -f rtf -l javascript -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"
alias hlc="pbpaste | pygmentize -f rtf -l css        -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"
alias hlh="pbpaste | pygmentize -f rtf -l html       -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"

