#!/usr/bin/env bash

files=(
  $HOME/.dotfiles/lib/utils         # Utils
  $HOME/.dotfiles/bash/bash_options # Options
  $HOME/.dotfiles/bash/bash_exports # Exports
  $HOME/.dotfiles/bash/bash_aliases # Aliases
  $HOME/.dotfiles/bash/functions/*  # Functions
  $HOME/.dotfiles/bash/bash_prompt  # Custom bash prompt
  $HOME/.bash_profile.local         # Local and private settings not under version control (e.g. git credentials)
  $HOME/.dotfiles/bash/bash_paths   # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for i in ${!files[*]}
do
  if [[ -r ${files[$i]} ]]; then
    source ${files[$i]}
  fi
done

unset files

# Init rbenv
if type_exists rbenvs; then
  eval "$(rbenv init -)"
fi

# Init nvm
. ~/.nvm/nvm.sh

nvm use stable

# Git completion
if  [ -f $HOME/.dotfiles/git/git-completion.bash ]; then
  source $HOME/.dotfiles/git/git-completion.bash
fi

if [ -f `brew --prefix`/etc/bash_completion.d/hub.bash_completion.sh ]; then
  . `brew --prefix`/etc/bash_completion.d/hub.bash_completion.sh
fi

