#!/usr/bin/env bash

alias ls="ls --color=auto -AF"
alias ll="ls -l"
alias tree='tree -F --dirsfirst -C'
alias diff="colordiff"

if type_exists htop; then
  alias top="htop"
fi

alias hlj="pbpaste | pygmentize -f rtf -l javascript -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"
alias hlc="pbpaste | pygmentize -f rtf -l css        -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"
alias hlh="pbpaste | pygmentize -f rtf -l html       -O 'fontface=Menlo,style=tomorrownightbright' | pbcopy"

